In [8]:
import pandas as pd
from IPython.display import display

In [ ]:
df = pd.read_csv('../data/data.csv')
df.head()

,company,year,employees_start,employees_end,new_hires,layoffs,net_change,hiring_rate_pct,attrition_rate_pct,revenue_billions_usd,stock_price_change_pct,gdp_growth_us_pct,unemployment_rate_us_pct,is_estimated,confidence_level,data_quality_score
0,AMD,2001,13387,14400,2083,1070,1013,15.6,8.0,3.89,25.1,1.0,4.7,False,Medium,95
1,AMD,2002,14400,12500,0,1900,-1900,0.0,13.2,2.70,42.8,1.7,5.8,False,Medium,95
2,AMD,2003,12500,12000,0,500,-500,0.0,4.0,3.52,-1.8,2.8,6.0,False,Medium,95
3,AMD,2004,12000,11700,60,360,-300,0.5,3.0,5.00,-18.6,3.8,5.5,False,Medium,95
4,AMD,2005,11700,9860,0,1840,-1840,0.0,15.7,5.85,15.2,3.5,5.1,False,Medium,95

:

# Comandos de Visualização.

In [ ]:
print('----Ver colunas.----')
display(df.columns)
print('----Ver quantidade de Indexs.----')
display(df.index)
print('----Ver colunas específicas.----')
display(df[['company', 'year']])
print('----Localizar----')
display(df.iloc[1:5])

----Ver colunas.----

Index(['company', 'year', 'employees_start', 'employees_end', 'new_hires',
       'layoffs', 'net_change', 'hiring_rate_pct', 'attrition_rate_pct',
       'revenue_billions_usd', 'stock_price_change_pct', 'gdp_growth_us_pct',
       'unemployment_rate_us_pct', 'is_estimated', 'confidence_level',
       'data_quality_score'],
      dtype='str')

----Ver quantidade de Indexs.----

RangeIndex(start=0, stop=532, step=1)

----Ver colunas específicas.----

         company  year
0            AMD  2001
1            AMD  2002
2            AMD  2003
3            AMD  2004
4            AMD  2005
..           ...   ...
527  X (Twitter)  2021
528  X (Twitter)  2022
529  X (Twitter)  2023
530  X (Twitter)  2024
531  X (Twitter)  2025

[532 rows x 2 columns]

----Localizar----

,company,year,employees_start,employees_end,new_hires,layoffs,net_change,hiring_rate_pct,attrition_rate_pct,revenue_billions_usd,stock_price_change_pct,gdp_growth_us_pct,unemployment_rate_us_pct,is_estimated,confidence_level,data_quality_score
1,AMD,2002,14400,12500,0,1900,-1900,0.0,13.2,2.70,42.8,1.7,5.8,False,Medium,95
2,AMD,2003,12500,12000,0,500,-500,0.0,4.0,3.52,-1.8,2.8,6.0,False,Medium,95
3,AMD,2004,12000,11700,60,360,-300,0.5,3.0,5.00,-18.6,3.8,5.5,False,Medium,95
4,AMD,2005,11700,9860,0,1840,-1840,0.0,15.7,5.85,15.2,3.5,5.1,False,Medium,95

:

In [ ]:
print('----Filtrar Colunas x Dado----')
display(df.loc[df['company'] == 'AMD'])
print('----Sortear employees_end decrescente----')
display(df.sort_values('employees_end', ascending=False))

----Filtrar Colunas x Dado----

,company,year,employees_start,employees_end,new_hires,layoffs,net_change,hiring_rate_pct,attrition_rate_pct,revenue_billions_usd,stock_price_change_pct,gdp_growth_us_pct,unemployment_rate_us_pct,is_estimated,confidence_level,data_quality_score
0,AMD,2001,13387,14400,2083,1070,1013,15.6,8.0,3.89,25.1,1.0,4.7,False,Medium,95
1,AMD,2002,14400,12500,0,1900,-1900,0.0,13.2,2.70,42.8,1.7,5.8,False,Medium,95
2,AMD,2003,12500,12000,0,500,-500,0.0,4.0,3.52,-1.8,2.8,6.0,False,Medium,95
3,AMD,2004,12000,11700,60,360,-300,0.5,3.0,5.00,-18.6,3.8,5.5,False,Medium,95
4,AMD,2005,11700,9860,0,1840,-1840,0.0,15.7,5.85,15.2,3.5,5.1,False,Medium,95
5,AMD,2006,9860,16000,6435,295,6140,65.3,3.0,5.65,47.2,2.8,4.6,False,Medium,95
6,AMD,2007,16000,16420,900,480,420,5.6,3.0,6.01,-8.1,2.0,4.6,False,Medium,95
7,AMD,2008,16420,10300,0,6120,-6120,0.0,37.3,5.81,-19.7,0.1,5.8,False,Medium,95
8,AMD,2009,10300,10400,924,824,100,9.0,8.0,5.40,35.6,-2.6,9.3,False,Medium,95
9,AMD,2010,10400,11100,1012,312,700,9.7,3.0,6.49,0.0,2.7,9.6,False,High,95
10,AMD,2011,11100,11100,333,333,0,3.0,3.0,6.57,-27.6,1.6,8.9,False,High,95
11,AMD,2012,11100,10600,0,500,-500,0.0,4.5,5.42,38.7,2.3,8.1,False,High,95
12,AMD,2013,10600,10149,0,451,-451,0.0,4.3,5.30,7.4,1.8,7.4,False,High,95
13,AMD,2014,10149,9700,0,449,-449,0.0,4.4,5.51,2.9,2.5,6.2,False,High,95
14,AMD,2015,9700,9700,291,291,0,3.0,3.0,3.99,43.8,2.9,5.3,False,High,95
15,AMD,2016,9700,8900,0,800,-800,0.0,8.2,4.27,40.9,1.6,4.9,False,High,95
16,AMD,2017,8900,9100,467,267,200,5.2,3.0,5.33,-4.8,2.4,4.4,False,High,95
17,AMD,2018,9100,10100,1273,273,1000,14.0,3.0,6.48,34.7,2.9,3.9,False,High,95
18,AMD,2019,10100,11400,1603,303,1300,15.9,3.0,6.73,36.8,2.3,3.7,False,High,95
19,AMD,2020,11400,13900,2842,342,2500,24.9,3.0,9.76,18.6,-2.8,8.1,False,High,95
20,AMD,2021,13900,15500,2017,417,1600,14.5,3.0,16.43,43.6,5.8,5.4,False,High,95
21,AMD,2022,15500,26000,11430,930,10500,73.7,6.0,23.60,-23.5,1.9,3.6,False,High,95
22,AMD,2023,26000,26000,1560,1560,0,6.0,6.0,22.68,40.5,2.5,3.7,False,High,95
23,AMD,2024,26000,28000,2780,780,2000,10.7,3.0,25.80,28.6,2.8,4.1,True,Medium,85
24,AMD,2025,28000,29000,1840,840,1000,6.6,3.0,28.50,22.5,2.3,4.2,True,Medium,85

----Sortear employees_end decrescente----

,company,year,employees_start,employees_end,new_hires,layoffs,net_change,hiring_rate_pct,attrition_rate_pct,revenue_billions_usd,stock_price_change_pct,gdp_growth_us_pct,unemployment_rate_us_pct,is_estimated,confidence_level,data_quality_score
109,Amazon,2021,1298000,1608000,348940,38940,310000,26.9,3.0,469.82,72.4,5.8,5.4,False,High,95
112,Amazon,2024,1525000,1556000,76750,45750,31000,5.0,3.0,620.00,42.7,2.8,4.1,True,Medium,85
110,Amazon,2022,1608000,1541000,29480,96480,-67000,1.8,6.0,514.00,-52.6,1.9,3.6,False,High,95
113,Amazon,2025,1556000,1540000,30680,46680,-16000,2.0,3.0,670.00,-2.9,2.3,4.2,True,Medium,85
111,Amazon,2023,1541000,1525000,76460,92460,-16000,5.0,6.0,575.00,42.8,2.5,3.7,False,High,95
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
426,Shopify,2007,10,20,10,0,10,100.0,0.0,0.01,-3.9,2.0,4.6,False,Medium,95
425,Shopify,2006,8,10,2,0,2,25.0,0.0,0.00,-6.5,2.8,4.6,False,Medium,95
459,Stripe,2011,8,10,2,0,2,25.0,0.0,0.01,46.4,1.6,8.9,True,Medium,85
512,X (Twitter),2006,8,10,2,0,2,25.0,0.0,0.00,-28.7,2.8,4.6,False,Medium,95
496,Uber,2010,8,10,2,0,2,25.0,0.0,0.00,31.0,2.7,9.6,False,High,95

:

# Adicionando uma Coluna

In [ ]:
df["employee_growth_pct"] = (df["net_change"] / df["employees_start"]) * 100

df["layoff_ratio"] = df["layoffs"] / df["employees_start"]

: