In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('data/data1.csv')

In [4]:
df.head(5)

,company,year,employees_start,employees_end,new_hires,layoffs,net_change,hiring_rate_pct,attrition_rate_pct,revenue_billions_usd,stock_price_change_pct,gdp_growth_us_pct,unemployment_rate_us_pct,is_estimated,confidence_level,data_quality_score,employee_growth_pct,layoff_ratio
0,AMD,2001,13387,14400,2083,1070,1013,15.6,8.0,3.89,25.1,1.0,4.7,False,Medium,95,7.567043,0.079928
1,AMD,2002,14400,12500,0,1900,-1900,0.0,13.2,2.70,42.8,1.7,5.8,False,Medium,95,-13.194444,0.131944
2,AMD,2003,12500,12000,0,500,-500,0.0,4.0,3.52,-1.8,2.8,6.0,False,Medium,95,-4.000000,0.040000
3,AMD,2004,12000,11700,60,360,-300,0.5,3.0,5.00,-18.6,3.8,5.5,False,Medium,95,-2.500000,0.030000
4,AMD,2005,11700,9860,0,1840,-1840,0.0,15.7,5.85,15.2,3.5,5.1,False,Medium,95,-15.726496,0.157265

In [5]:
print(df.dtypes)

company                         str
year                          int64
employees_start               int64
employees_end                 int64
new_hires                     int64
layoffs                       int64
net_change                    int64
hiring_rate_pct             float64
attrition_rate_pct          float64
revenue_billions_usd        float64
stock_price_change_pct      float64
gdp_growth_us_pct           float64
unemployment_rate_us_pct    float64
is_estimated                   bool
confidence_level                str
data_quality_score            int64
employee_growth_pct         float64
layoff_ratio                float64
dtype: object

# Filtrando Dados

In [6]:
filter1 = df.loc[df['new_hires'] == 0]
filter1

,company,year,employees_start,employees_end,new_hires,layoffs,net_change,hiring_rate_pct,attrition_rate_pct,revenue_billions_usd,stock_price_change_pct,gdp_growth_us_pct,unemployment_rate_us_pct,is_estimated,confidence_level,data_quality_score,employee_growth_pct,layoff_ratio
1,AMD,2002,14400,12500,0,1900,-1900,0.0,13.2,2.70,42.8,1.7,5.8,False,Medium,95,-13.194444,0.131944
2,AMD,2003,12500,12000,0,500,-500,0.0,4.0,3.52,-1.8,2.8,6.0,False,Medium,95,-4.000000,0.040000
4,AMD,2005,11700,9860,0,1840,-1840,0.0,15.7,5.85,15.2,3.5,5.1,False,Medium,95,-15.726496,0.157265
7,AMD,2008,16420,10300,0,6120,-6120,0.0,37.3,5.81,-19.7,0.1,5.8,False,Medium,95,-37.271620,0.372716
11,AMD,2012,11100,10600,0,500,-500,0.0,4.5,5.42,38.7,2.3,8.1,False,High,95,-4.504505,0.045045
12,AMD,2013,10600,10149,0,451,-451,0.0,4.3,5.30,7.4,1.8,7.4,False,High,95,-4.254717,0.042547
13,AMD,2014,10149,9700,0,449,-449,0.0,4.4,5.51,2.9,2.5,6.2,False,High,95,-4.424081,0.044241
15,AMD,2016,9700,8900,0,800,-800,0.0,8.2,4.27,40.9,1.6,4.9,False,High,95,-8.247423,0.082474
29,Adobe,2005,3300,3142,0,158,-158,0.0,4.8,1.97,48.8,3.5,5.1,False,Medium,95,-4.787879,0.047879
33,Adobe,2009,7335,6735,0,600,-600,0.0,8.2,2.95,31.5,-2.6,9.3,False,Medium,95,-8.179959,0.081800
61,Airbnb,2020,6100,5600,0,500,-500,0.0,8.2,3.38,93.4,-2.8,8.1,True,Medium,85,-8.196721,0.081967
76,Alphabet,2013,53861,47756,0,6105,-6105,0.0,11.3,55.52,35.6,1.8,7.4,False,High,95,-11.334732,0.113347
89,Amazon,2001,9000,7800,0,1200,-1200,0.0,13.3,3.12,-7.5,1.0,4.7,False,Medium,95,-13.333333,0.133333
152,Block,2023,13000,12000,0,1000,-1000,0.0,7.7,21.32,106.4,2.5,3.7,True,Medium,85,-7.692308,0.076923
160,Intel,2006,99900,94100,0,5800,-5800,0.0,5.8,35.38,32.0,2.8,4.6,False,Medium,95,-5.805806,0.058058
161,Intel,2007,94100,86300,0,7800,-7800,0.0,8.3,38.33,-23.1,2.0,4.6,False,Medium,95,-8.289054,0.082891
171,Intel,2017,106000,102700,0,3300,-3300,0.0,3.1,62.76,-3.0,2.4,4.4,False,High,95,-3.113208,0.031132
178,Intel,2024,124800,116500,0,8300,-8300,0.0,6.7,54.20,29.8,2.8,4.1,True,Medium,85,-6.650641,0.066506
179,Intel,2025,116500,110000,0,6500,-6500,0.0,5.6,55.00,26.9,2.3,4.2,True,Medium,85,-5.579399,0.055794
209,Lyft,2020,5100,4800,0,300,-300,0.0,5.9,2.36,56.1,-2.8,8.1,True,Medium,85,-5.882353,0.058824
212,Lyft,2023,5900,4500,0,1400,-1400,0.0,23.7,4.10,23.7,2.5,3.7,True,Medium,85,-23.728814,0.237288
232,Meta,2023,86482,67317,0,19165,-19165,0.0,22.2,134.90,86.8,2.5,3.7,False,High,95,-22.160681,0.221607
244,Microsoft,2010,93000,89000,0,4000,-4000,0.0,4.3,62.48,19.5,2.7,9.6,False,High,95,-4.301075,0.043011
249,Microsoft,2015,128000,118000,0,10000,-10000,0.0,7.8,93.58,12.9,2.9,5.3,False,High,95,-7.812500,0.078125
250,Microsoft,2016,118000,114000,0,4000,-4000,0.0,3.4,91.15,-13.8,1.6,4.9,False,High,95,-3.389831,0.033898
285,Netflix,2001,120,100,0,20,-20,0.0,16.7,0.08,-21.3,1.0,4.7,False,Medium,95,-16.666667,0.166667
296,Netflix,2012,2348,2022,0,326,-326,0.0,13.9,3.61,0.7,2.3,8.1,False,High,95,-13.884157,0.138842
357,PayPal,2023,30000,27500,0,2500,-2500,0.0,8.3,29.77,112.5,2.5,3.7,False,High,95,-8.333333,0.083333
372,Pinterest,2023,4100,3400,0,700,-700,0.0,17.1,3.03,73.2,2.5,3.7,True,Medium,85,-17.073171,0.170732
422,Salesforce,2023,79390,72682,0,6708,-6708,0.0,8.4,34.86,74.7,2.5,3.7,False,High,95,-8.449427,0.084494
442,Shopify,2023,11600,10000,0,1600,-1600,0.0,13.8,7.06,109.9,2.5,3.7,False,High,95,-13.793103,0.137931
456,Snap,2023,6446,5661,0,785,-785,0.0,12.2,4.60,63.9,2.5,3.7,True,Medium,85,-12.178095,0.121781
471,Stripe,2023,8000,7400,0,600,-600,0.0,7.5,14.40,78.1,2.5,3.7,True,Medium,85,-7.500000,0.075000
506,Uber,2020,26900,23200,0,3700,-3700,0.0,13.8,11.14,-8.5,-2.8,8.1,False,High,95,-13.754647,0.137546
522,X (Twitter),2016,3900,3583,0,317,-317,0.0,8.1,2.53,10.7,1.6,4.9,False,High,95,-8.128205,0.081282
523,X (Twitter),2017,3583,3200,0,383,-383,0.0,10.7,2.44,-12.4,2.4,4.4,False,High,95,-10.689366,0.106894
529,X (Twitter),2023,8000,1500,0,6500,-6500,0.0,81.2,3.40,22.0,2.5,3.7,False,High,95,-81.250000,0.812500

In [7]:
filter2 = df.loc[df['new_hires'] > 2000]
filter2

,company,year,employees_start,employees_end,new_hires,layoffs,net_change,hiring_rate_pct,attrition_rate_pct,revenue_billions_usd,stock_price_change_pct,gdp_growth_us_pct,unemployment_rate_us_pct,is_estimated,confidence_level,data_quality_score,employee_growth_pct,layoff_ratio
0,AMD,2001,13387,14400,2083,1070,1013,15.6,8.0,3.89,25.1,1.0,4.7,False,Medium,95,7.567043,0.079928
5,AMD,2006,9860,16000,6435,295,6140,65.3,3.0,5.65,47.2,2.8,4.6,False,Medium,95,62.271805,0.029919
19,AMD,2020,11400,13900,2842,342,2500,24.9,3.0,9.76,18.6,-2.8,8.1,False,High,95,21.929825,0.030000
20,AMD,2021,13900,15500,2017,417,1600,14.5,3.0,16.43,43.6,5.8,5.4,False,High,95,11.510791,0.030000
21,AMD,2022,15500,26000,11430,930,10500,73.7,6.0,23.60,-23.5,1.9,3.6,False,High,95,67.741935,0.060000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
505,Uber,2019,22263,26900,5304,667,4637,23.8,3.0,14.15,48.6,2.3,3.7,False,High,95,20.828280,0.029960
507,Uber,2021,23200,29300,6796,696,6100,29.3,3.0,17.46,17.6,5.8,5.4,False,High,95,26.293103,0.030000
508,Uber,2022,29300,32200,4658,1758,2900,15.9,6.0,31.88,-32.5,1.9,3.6,False,High,95,9.897611,0.060000
510,Uber,2024,32200,33500,2266,966,1300,7.0,3.0,43.00,-5.2,2.8,4.1,True,Medium,85,4.037267,0.030000
511,Uber,2025,33500,34500,2005,1005,1000,6.0,3.0,48.00,24.1,2.3,4.2,True,Medium,85,2.985075,0.030000

In [8]:
filter3 = df.loc[(df['new_hires'] > 2000) & (df['layoffs'] == 1070)]
filter3

,company,year,employees_start,employees_end,new_hires,layoffs,net_change,hiring_rate_pct,attrition_rate_pct,revenue_billions_usd,stock_price_change_pct,gdp_growth_us_pct,unemployment_rate_us_pct,is_estimated,confidence_level,data_quality_score,employee_growth_pct,layoff_ratio
0,AMD,2001,13387,14400,2083,1070,1013,15.6,8.0,3.89,25.1,1.0,4.7,False,Medium,95,7.567043,0.079928

In [9]:
import re
filter4 = df.loc[df['company'].str.contains('AMD| Samsung', flags=re.I)]
filter4

,company,year,employees_start,employees_end,new_hires,layoffs,net_change,hiring_rate_pct,attrition_rate_pct,revenue_billions_usd,stock_price_change_pct,gdp_growth_us_pct,unemployment_rate_us_pct,is_estimated,confidence_level,data_quality_score,employee_growth_pct,layoff_ratio
0,AMD,2001,13387,14400,2083,1070,1013,15.6,8.0,3.89,25.1,1.0,4.7,False,Medium,95,7.567043,0.079928
1,AMD,2002,14400,12500,0,1900,-1900,0.0,13.2,2.70,42.8,1.7,5.8,False,Medium,95,-13.194444,0.131944
2,AMD,2003,12500,12000,0,500,-500,0.0,4.0,3.52,-1.8,2.8,6.0,False,Medium,95,-4.000000,0.040000
3,AMD,2004,12000,11700,60,360,-300,0.5,3.0,5.00,-18.6,3.8,5.5,False,Medium,95,-2.500000,0.030000
4,AMD,2005,11700,9860,0,1840,-1840,0.0,15.7,5.85,15.2,3.5,5.1,False,Medium,95,-15.726496,0.157265
5,AMD,2006,9860,16000,6435,295,6140,65.3,3.0,5.65,47.2,2.8,4.6,False,Medium,95,62.271805,0.029919
6,AMD,2007,16000,16420,900,480,420,5.6,3.0,6.01,-8.1,2.0,4.6,False,Medium,95,2.625000,0.030000
7,AMD,2008,16420,10300,0,6120,-6120,0.0,37.3,5.81,-19.7,0.1,5.8,False,Medium,95,-37.271620,0.372716
8,AMD,2009,10300,10400,924,824,100,9.0,8.0,5.40,35.6,-2.6,9.3,False,Medium,95,0.970874,0.080000
9,AMD,2010,10400,11100,1012,312,700,9.7,3.0,6.49,0.0,2.7,9.6,False,High,95,6.730769,0.030000
10,AMD,2011,11100,11100,333,333,0,3.0,3.0,6.57,-27.6,1.6,8.9,False,High,95,0.000000,0.030000
11,AMD,2012,11100,10600,0,500,-500,0.0,4.5,5.42,38.7,2.3,8.1,False,High,95,-4.504505,0.045045
12,AMD,2013,10600,10149,0,451,-451,0.0,4.3,5.30,7.4,1.8,7.4,False,High,95,-4.254717,0.042547
13,AMD,2014,10149,9700,0,449,-449,0.0,4.4,5.51,2.9,2.5,6.2,False,High,95,-4.424081,0.044241
14,AMD,2015,9700,9700,291,291,0,3.0,3.0,3.99,43.8,2.9,5.3,False,High,95,0.000000,0.030000
15,AMD,2016,9700,8900,0,800,-800,0.0,8.2,4.27,40.9,1.6,4.9,False,High,95,-8.247423,0.082474
16,AMD,2017,8900,9100,467,267,200,5.2,3.0,5.33,-4.8,2.4,4.4,False,High,95,2.247191,0.030000
17,AMD,2018,9100,10100,1273,273,1000,14.0,3.0,6.48,34.7,2.9,3.9,False,High,95,10.989011,0.030000
18,AMD,2019,10100,11400,1603,303,1300,15.9,3.0,6.73,36.8,2.3,3.7,False,High,95,12.871287,0.030000
19,AMD,2020,11400,13900,2842,342,2500,24.9,3.0,9.76,18.6,-2.8,8.1,False,High,95,21.929825,0.030000
20,AMD,2021,13900,15500,2017,417,1600,14.5,3.0,16.43,43.6,5.8,5.4,False,High,95,11.510791,0.030000
21,AMD,2022,15500,26000,11430,930,10500,73.7,6.0,23.60,-23.5,1.9,3.6,False,High,95,67.741935,0.060000
22,AMD,2023,26000,26000,1560,1560,0,6.0,6.0,22.68,40.5,2.5,3.7,False,High,95,0.000000,0.060000
23,AMD,2024,26000,28000,2780,780,2000,10.7,3.0,25.80,28.6,2.8,4.1,True,Medium,85,7.692308,0.030000
24,AMD,2025,28000,29000,1840,840,1000,6.6,3.0,28.50,22.5,2.3,4.2,True,Medium,85,3.571429,0.030000

In [10]:
filter5 = df.loc[
    (df['year'] >= 2000) &
    (df['year'] < 2010) &
    (df['company'] == 'AMD')
]

filter5

,company,year,employees_start,employees_end,new_hires,layoffs,net_change,hiring_rate_pct,attrition_rate_pct,revenue_billions_usd,stock_price_change_pct,gdp_growth_us_pct,unemployment_rate_us_pct,is_estimated,confidence_level,data_quality_score,employee_growth_pct,layoff_ratio
0,AMD,2001,13387,14400,2083,1070,1013,15.6,8.0,3.89,25.1,1.0,4.7,False,Medium,95,7.567043,0.079928
1,AMD,2002,14400,12500,0,1900,-1900,0.0,13.2,2.70,42.8,1.7,5.8,False,Medium,95,-13.194444,0.131944
2,AMD,2003,12500,12000,0,500,-500,0.0,4.0,3.52,-1.8,2.8,6.0,False,Medium,95,-4.000000,0.040000
3,AMD,2004,12000,11700,60,360,-300,0.5,3.0,5.00,-18.6,3.8,5.5,False,Medium,95,-2.500000,0.030000
4,AMD,2005,11700,9860,0,1840,-1840,0.0,15.7,5.85,15.2,3.5,5.1,False,Medium,95,-15.726496,0.157265
5,AMD,2006,9860,16000,6435,295,6140,65.3,3.0,5.65,47.2,2.8,4.6,False,Medium,95,62.271805,0.029919
6,AMD,2007,16000,16420,900,480,420,5.6,3.0,6.01,-8.1,2.0,4.6,False,Medium,95,2.625000,0.030000
7,AMD,2008,16420,10300,0,6120,-6120,0.0,37.3,5.81,-19.7,0.1,5.8,False,Medium,95,-37.271620,0.372716
8,AMD,2009,10300,10400,924,824,100,9.0,8.0,5.40,35.6,-2.6,9.3,False,Medium,95,0.970874,0.080000

# Modificando Dados

In [11]:
df.loc[df['confidence_level'] == 'Medium', 'confidence_level'] = 'Médio'
filter5

,company,year,employees_start,employees_end,new_hires,layoffs,net_change,hiring_rate_pct,attrition_rate_pct,revenue_billions_usd,stock_price_change_pct,gdp_growth_us_pct,unemployment_rate_us_pct,is_estimated,confidence_level,data_quality_score,employee_growth_pct,layoff_ratio
0,AMD,2001,13387,14400,2083,1070,1013,15.6,8.0,3.89,25.1,1.0,4.7,False,Medium,95,7.567043,0.079928
1,AMD,2002,14400,12500,0,1900,-1900,0.0,13.2,2.70,42.8,1.7,5.8,False,Medium,95,-13.194444,0.131944
2,AMD,2003,12500,12000,0,500,-500,0.0,4.0,3.52,-1.8,2.8,6.0,False,Medium,95,-4.000000,0.040000
3,AMD,2004,12000,11700,60,360,-300,0.5,3.0,5.00,-18.6,3.8,5.5,False,Medium,95,-2.500000,0.030000
4,AMD,2005,11700,9860,0,1840,-1840,0.0,15.7,5.85,15.2,3.5,5.1,False,Medium,95,-15.726496,0.157265
5,AMD,2006,9860,16000,6435,295,6140,65.3,3.0,5.65,47.2,2.8,4.6,False,Medium,95,62.271805,0.029919
6,AMD,2007,16000,16420,900,480,420,5.6,3.0,6.01,-8.1,2.0,4.6,False,Medium,95,2.625000,0.030000
7,AMD,2008,16420,10300,0,6120,-6120,0.0,37.3,5.81,-19.7,0.1,5.8,False,Medium,95,-37.271620,0.372716
8,AMD,2009,10300,10400,924,824,100,9.0,8.0,5.40,35.6,-2.6,9.3,False,Medium,95,0.970874,0.080000

# GroupBy

In [ ]:
df.groupby(['company']).count()

,year,employees_start,employees_end,new_hires,layoffs,net_change,hiring_rate_pct,attrition_rate_pct,revenue_billions_usd,stock_price_change_pct,gdp_growth_us_pct,unemployment_rate_us_pct,is_estimated,confidence_level,data_quality_score,employee_growth_pct,layoff_ratio
company,,,,,,,,,,,,,,,,,
Amazon,50325,10690400,12221400,1949387,418387,1531000,729.6,106.3,4572.92,295.8,50.6,142.9,2,MédioMédioMédioMédioMédioMédioMédioMédioMédioH...,2355,623.101615,1.063333
Microsoft,50325,2789200,2978100,305301,116401,188900,298.3,107.5,2501.37,348.0,50.6,142.9,2,MédioMédioMédioMédioMédioMédioMédioMédioMédioH...,2355,190.966815,1.075034
Oracle,50325,2595681,2716361,219914,99234,120680,251.1,101.0,795.91,406.2,50.6,142.9,2,MédioMédioMédioMédioMédioMédioMédioMédioMédioH...,2355,149.964304,1.009925
Intel,50325,2497900,2521800,138873,114973,23900,146.3,115.5,1266.14,324.2,50.6,142.9,2,MédioMédioMédioMédioMédioMédioMédioMédioMédioH...,2355,30.765888,1.154381
Apple,50325,1932555,2089987,228536,71104,157432,429.2,101.0,4265.09,381.5,50.6,142.9,2,MédioMédioMédioMédioMédioMédioMédioMédioMédioH...,2355,328.251979,1.009914
SAP,50325,1651087,1738087,150318,63318,87000,263.8,101.0,537.46,403.3,50.6,142.9,2,MédioMédioMédioMédioMédioMédioMédioMédioMédioH...,2355,162.723566,1.009934
Alphabet,44319,1570395,1752828,246281,63848,182433,617.7,90.3,2656.10,293.3,45.1,126.4,2,MédioMédioMédioMédioMédioMédioHighHighHighHigh...,2070,527.419223,0.902933
Tesla,44319,767220,905178,167821,29863,137958,1192.4,79.7,545.50,187.8,45.1,126.4,2,MédioMédioMédioMédioMédioMédioHighHighHighHigh...,2070,1112.936020,0.795567
Salesforce,50325,530484,602444,94648,22688,71960,1139.0,102.8,268.09,370.6,50.6,142.9,2,MédioMédioMédioMédioMédioMédioMédioMédioMédioH...,2355,1035.957190,1.028655
Meta,40310,521922,600245,112761,34438,78323,945.5,91.3,1045.03,372.3,37.8,115.8,2,MédioMédioMédioMédioHighHighHighHighHighHighHi...,1880,854.239918,0.911144

In [19]:
df.groupby(['company']).sum().sort_values('employees_start', ascending=False).head(10)

,year,employees_start,employees_end,new_hires,layoffs,net_change,hiring_rate_pct,attrition_rate_pct,revenue_billions_usd,stock_price_change_pct,gdp_growth_us_pct,unemployment_rate_us_pct,is_estimated,confidence_level,data_quality_score,employee_growth_pct,layoff_ratio
company,,,,,,,,,,,,,,,,,
Amazon,50325,10690400,12221400,1949387,418387,1531000,729.6,106.3,4572.92,295.8,50.6,142.9,2,MédioMédioMédioMédioMédioMédioMédioMédioMédioH...,2355,623.101615,1.063333
Microsoft,50325,2789200,2978100,305301,116401,188900,298.3,107.5,2501.37,348.0,50.6,142.9,2,MédioMédioMédioMédioMédioMédioMédioMédioMédioH...,2355,190.966815,1.075034
Oracle,50325,2595681,2716361,219914,99234,120680,251.1,101.0,795.91,406.2,50.6,142.9,2,MédioMédioMédioMédioMédioMédioMédioMédioMédioH...,2355,149.964304,1.009925
Intel,50325,2497900,2521800,138873,114973,23900,146.3,115.5,1266.14,324.2,50.6,142.9,2,MédioMédioMédioMédioMédioMédioMédioMédioMédioH...,2355,30.765888,1.154381
Apple,50325,1932555,2089987,228536,71104,157432,429.2,101.0,4265.09,381.5,50.6,142.9,2,MédioMédioMédioMédioMédioMédioMédioMédioMédioH...,2355,328.251979,1.009914
SAP,50325,1651087,1738087,150318,63318,87000,263.8,101.0,537.46,403.3,50.6,142.9,2,MédioMédioMédioMédioMédioMédioMédioMédioMédioH...,2355,162.723566,1.009934
Alphabet,44319,1570395,1752828,246281,63848,182433,617.7,90.3,2656.10,293.3,45.1,126.4,2,MédioMédioMédioMédioMédioMédioHighHighHighHigh...,2070,527.419223,0.902933
Tesla,44319,767220,905178,167821,29863,137958,1192.4,79.7,545.50,187.8,45.1,126.4,2,MédioMédioMédioMédioMédioMédioHighHighHighHigh...,2070,1112.936020,0.795567
Salesforce,50325,530484,602444,94648,22688,71960,1139.0,102.8,268.09,370.6,50.6,142.9,2,MédioMédioMédioMédioMédioMédioMédioMédioMédioH...,2355,1035.957190,1.028655
Meta,40310,521922,600245,112761,34438,78323,945.5,91.3,1045.03,372.3,37.8,115.8,2,MédioMédioMédioMédioHighHighHighHighHighHighHi...,1880,854.239918,0.911144

In [20]:
df.groupby(['company']).count().sort_values('employees_start', ascending=False).head(10)

,year,employees_start,employees_end,new_hires,layoffs,net_change,hiring_rate_pct,attrition_rate_pct,revenue_billions_usd,stock_price_change_pct,gdp_growth_us_pct,unemployment_rate_us_pct,is_estimated,confidence_level,data_quality_score,employee_growth_pct,layoff_ratio
company,,,,,,,,,,,,,,,,,
AMD,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25
Adobe,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25
Amazon,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25
Intel,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25
Apple,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25
Netflix,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25
Oracle,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25
Microsoft,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25
NVIDIA,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25
PayPal,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25